
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.browndog.moreores.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.Registry;

import net.browndog.moreores.block.ZinkOreBlock;
import net.browndog.moreores.block.ZinkBlockBlock;
import net.browndog.moreores.block.YellowDiamondOreBlock;
import net.browndog.moreores.block.YellowDiamondBlockBlock;
import net.browndog.moreores.block.TopazOreBlock;
import net.browndog.moreores.block.TopazBlockBlock;
import net.browndog.moreores.block.TitaniumOreBlock;
import net.browndog.moreores.block.TitaniumBlockBlock;
import net.browndog.moreores.block.TinOreBlock;
import net.browndog.moreores.block.TinBlockBlock;
import net.browndog.moreores.block.TanzaniteOreBlock;
import net.browndog.moreores.block.TanzaniteBlockBlock;
import net.browndog.moreores.block.SteelOreBlock;
import net.browndog.moreores.block.SteelBlockBlock;
import net.browndog.moreores.block.SliverOreBlock;
import net.browndog.moreores.block.SliverBlockBlock;
import net.browndog.moreores.block.SapphireOreBlock;
import net.browndog.moreores.block.SapphireBlockBlock;
import net.browndog.moreores.block.RubyOreBlock;
import net.browndog.moreores.block.RubyBlockBlock;
import net.browndog.moreores.block.Red_DiamondOreBlock;
import net.browndog.moreores.block.Red_DiamondBlockBlock;
import net.browndog.moreores.block.PurpleDiamondOreBlock;
import net.browndog.moreores.block.PurpleDiamondBlockBlock;
import net.browndog.moreores.block.PlatinumOreBlock;
import net.browndog.moreores.block.PlatinumBlockBlock;
import net.browndog.moreores.block.OrangeDiamondOreBlock;
import net.browndog.moreores.block.OrangeDiamondBlockBlock;
import net.browndog.moreores.block.OpalOreBlock;
import net.browndog.moreores.block.OpalBlockBlock;
import net.browndog.moreores.block.NickelOreBlock;
import net.browndog.moreores.block.NickelBlockBlock;
import net.browndog.moreores.block.LuminousGemOreBlock;
import net.browndog.moreores.block.LuminousGemBlockBlock;
import net.browndog.moreores.block.LithiumOreBlock;
import net.browndog.moreores.block.LithiumBlockBlock;
import net.browndog.moreores.block.GreenDiamondOreBlock;
import net.browndog.moreores.block.GreenDiamondBlockBlock;
import net.browndog.moreores.block.BlueDiamondOreBlock;
import net.browndog.moreores.block.BlueDiamondBlockBlock;
import net.browndog.moreores.block.BlackDiamondOreBlock;
import net.browndog.moreores.block.BlackDiamondBlockBlock;
import net.browndog.moreores.block.AetheriumOreBlock;
import net.browndog.moreores.block.AetheriumBlockBlock;
import net.browndog.moreores.BrowndogOresMod;

public class BrowndogOresModBlocks {
	public static Block AETHERIUM_ORE;
	public static Block AETHERIUM_BLOCK;
	public static Block SLIVER_ORE;
	public static Block SLIVER_BLOCK;
	public static Block STEEL_ORE;
	public static Block STEEL_BLOCK;
	public static Block NICKEL_ORE;
	public static Block NICKEL_BLOCK;
	public static Block RUBY_ORE;
	public static Block RUBY_BLOCK;
	public static Block SAPPHIRE_ORE;
	public static Block SAPPHIRE_BLOCK;
	public static Block TOPAZ_ORE;
	public static Block TOPAZ_BLOCK;
	public static Block OPAL_ORE;
	public static Block OPAL_BLOCK;
	public static Block TITANIUM_ORE;
	public static Block TITANIUM_BLOCK;
	public static Block TANZANITE_ORE;
	public static Block TANZANITE_BLOCK;
	public static Block LUMINOUS_GEM_ORE;
	public static Block LUMINOUS_GEM_BLOCK;
	public static Block ZINK_ORE;
	public static Block ZINK_BLOCK;
	public static Block LITHIUM_ORE;
	public static Block LITHIUM_BLOCK;
	public static Block TIN_ORE;
	public static Block TIN_BLOCK;
	public static Block PLATINUM_ORE;
	public static Block PLATINUM_BLOCK;
	public static Block RED_DIAMOND_ORE;
	public static Block RED_DIAMOND_BLOCK;
	public static Block ORANGE_DIAMOND_ORE;
	public static Block ORANGE_DIAMOND_BLOCK;
	public static Block YELLOW_DIAMOND_ORE;
	public static Block YELLOW_DIAMOND_BLOCK;
	public static Block BLACK_DIAMOND_ORE;
	public static Block BLACK_DIAMOND_BLOCK;
	public static Block GREEN_DIAMOND_ORE;
	public static Block GREEN_DIAMOND_BLOCK;
	public static Block BLUE_DIAMOND_ORE;
	public static Block BLUE_DIAMOND_BLOCK;
	public static Block PURPLE_DIAMOND_ORE;
	public static Block PURPLE_DIAMOND_BLOCK;

	public static void load() {
		AETHERIUM_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_ore"), new AetheriumOreBlock());
		AETHERIUM_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_block"), new AetheriumBlockBlock());
		SLIVER_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "sliver_ore"), new SliverOreBlock());
		SLIVER_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "sliver_block"), new SliverBlockBlock());
		STEEL_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "steel_ore"), new SteelOreBlock());
		STEEL_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "steel_block"), new SteelBlockBlock());
		NICKEL_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "nickel_ore"), new NickelOreBlock());
		NICKEL_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "nickel_block"), new NickelBlockBlock());
		RUBY_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "ruby_ore"), new RubyOreBlock());
		RUBY_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "ruby_block"), new RubyBlockBlock());
		SAPPHIRE_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_ore"), new SapphireOreBlock());
		SAPPHIRE_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_block"), new SapphireBlockBlock());
		TOPAZ_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "topaz_ore"), new TopazOreBlock());
		TOPAZ_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "topaz_block"), new TopazBlockBlock());
		OPAL_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "opal_ore"), new OpalOreBlock());
		OPAL_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "opal_block"), new OpalBlockBlock());
		TITANIUM_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "titanium_ore"), new TitaniumOreBlock());
		TITANIUM_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "titanium_block"), new TitaniumBlockBlock());
		TANZANITE_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_ore"), new TanzaniteOreBlock());
		TANZANITE_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_block"), new TanzaniteBlockBlock());
		LUMINOUS_GEM_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_ore"), new LuminousGemOreBlock());
		LUMINOUS_GEM_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_block"), new LuminousGemBlockBlock());
		ZINK_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "zink_ore"), new ZinkOreBlock());
		ZINK_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "zink_block"), new ZinkBlockBlock());
		LITHIUM_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "lithium_ore"), new LithiumOreBlock());
		LITHIUM_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "lithium_block"), new LithiumBlockBlock());
		TIN_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "tin_ore"), new TinOreBlock());
		TIN_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "tin_block"), new TinBlockBlock());
		PLATINUM_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "platinum_ore"), new PlatinumOreBlock());
		PLATINUM_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "platinum_block"), new PlatinumBlockBlock());
		RED_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_ore"), new Red_DiamondOreBlock());
		RED_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_block"), new Red_DiamondBlockBlock());
		ORANGE_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_ore"), new OrangeDiamondOreBlock());
		ORANGE_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_block"), new OrangeDiamondBlockBlock());
		YELLOW_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_ore"), new YellowDiamondOreBlock());
		YELLOW_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_block"), new YellowDiamondBlockBlock());
		BLACK_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_ore"), new BlackDiamondOreBlock());
		BLACK_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_block"), new BlackDiamondBlockBlock());
		GREEN_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_ore"), new GreenDiamondOreBlock());
		GREEN_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_block"), new GreenDiamondBlockBlock());
		BLUE_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_ore"), new BlueDiamondOreBlock());
		BLUE_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_block"), new BlueDiamondBlockBlock());
		PURPLE_DIAMOND_ORE = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_ore"), new PurpleDiamondOreBlock());
		PURPLE_DIAMOND_BLOCK = Registry.register(Registry.BLOCK, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_block"), new PurpleDiamondBlockBlock());
	}

	public static void clientLoad() {
		AetheriumOreBlock.clientInit();
		AetheriumBlockBlock.clientInit();
		SliverOreBlock.clientInit();
		SliverBlockBlock.clientInit();
		SteelOreBlock.clientInit();
		SteelBlockBlock.clientInit();
		NickelOreBlock.clientInit();
		NickelBlockBlock.clientInit();
		RubyOreBlock.clientInit();
		RubyBlockBlock.clientInit();
		SapphireOreBlock.clientInit();
		SapphireBlockBlock.clientInit();
		TopazOreBlock.clientInit();
		TopazBlockBlock.clientInit();
		OpalOreBlock.clientInit();
		OpalBlockBlock.clientInit();
		TitaniumOreBlock.clientInit();
		TitaniumBlockBlock.clientInit();
		TanzaniteOreBlock.clientInit();
		TanzaniteBlockBlock.clientInit();
		LuminousGemOreBlock.clientInit();
		LuminousGemBlockBlock.clientInit();
		ZinkOreBlock.clientInit();
		ZinkBlockBlock.clientInit();
		LithiumOreBlock.clientInit();
		LithiumBlockBlock.clientInit();
		TinOreBlock.clientInit();
		TinBlockBlock.clientInit();
		PlatinumOreBlock.clientInit();
		PlatinumBlockBlock.clientInit();
		Red_DiamondOreBlock.clientInit();
		Red_DiamondBlockBlock.clientInit();
		OrangeDiamondOreBlock.clientInit();
		OrangeDiamondBlockBlock.clientInit();
		YellowDiamondOreBlock.clientInit();
		YellowDiamondBlockBlock.clientInit();
		BlackDiamondOreBlock.clientInit();
		BlackDiamondBlockBlock.clientInit();
		GreenDiamondOreBlock.clientInit();
		GreenDiamondBlockBlock.clientInit();
		BlueDiamondOreBlock.clientInit();
		BlueDiamondBlockBlock.clientInit();
		PurpleDiamondOreBlock.clientInit();
		PurpleDiamondBlockBlock.clientInit();
	}
}
