
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.browndog.moreores.init;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.Registry;

import net.browndog.moreores.item.ZinkSwordItem;
import net.browndog.moreores.item.ZinkShovelItem;
import net.browndog.moreores.item.ZinkPickaxeItem;
import net.browndog.moreores.item.ZinkIngotItem;
import net.browndog.moreores.item.ZinkHoeItem;
import net.browndog.moreores.item.ZinkAxeItem;
import net.browndog.moreores.item.ZinkArmorItem;
import net.browndog.moreores.item.YellowDiamondSwordItem;
import net.browndog.moreores.item.YellowDiamondShovelItem;
import net.browndog.moreores.item.YellowDiamondPickaxeItem;
import net.browndog.moreores.item.YellowDiamondItem;
import net.browndog.moreores.item.YellowDiamondHoeItem;
import net.browndog.moreores.item.YellowDiamondAxeItem;
import net.browndog.moreores.item.TopazSwordItem;
import net.browndog.moreores.item.TopazShovelItem;
import net.browndog.moreores.item.TopazPickaxeItem;
import net.browndog.moreores.item.TopazItem;
import net.browndog.moreores.item.TopazHoeItem;
import net.browndog.moreores.item.TopazAxeItem;
import net.browndog.moreores.item.TopazArmorItem;
import net.browndog.moreores.item.TitaniumSwordItem;
import net.browndog.moreores.item.TitaniumShovelItem;
import net.browndog.moreores.item.TitaniumPickaxeItem;
import net.browndog.moreores.item.TitaniumIngotItem;
import net.browndog.moreores.item.TitaniumHoeItem;
import net.browndog.moreores.item.TitaniumAxeItem;
import net.browndog.moreores.item.TitaniumArmorItem;
import net.browndog.moreores.item.TinSwordItem;
import net.browndog.moreores.item.TinShovelItem;
import net.browndog.moreores.item.TinPickaxeItem;
import net.browndog.moreores.item.TinIngotItem;
import net.browndog.moreores.item.TinHoeItem;
import net.browndog.moreores.item.TinAxeItem;
import net.browndog.moreores.item.TinArmorItem;
import net.browndog.moreores.item.TanzaniteSwordItem;
import net.browndog.moreores.item.TanzaniteShovelItem;
import net.browndog.moreores.item.TanzanitePickaxeItem;
import net.browndog.moreores.item.TanzaniteItem;
import net.browndog.moreores.item.TanzaniteHoeItem;
import net.browndog.moreores.item.TanzaniteAxeItem;
import net.browndog.moreores.item.TanzaniteArmorItem;
import net.browndog.moreores.item.SteelSwordItem;
import net.browndog.moreores.item.SteelShovelItem;
import net.browndog.moreores.item.SteelPickaxeItem;
import net.browndog.moreores.item.SteelIngotItem;
import net.browndog.moreores.item.SteelHoeItem;
import net.browndog.moreores.item.SteelAxeItem;
import net.browndog.moreores.item.SteelArmorItem;
import net.browndog.moreores.item.SliverSwordItem;
import net.browndog.moreores.item.SliverShovelItem;
import net.browndog.moreores.item.SliverPickaxeItem;
import net.browndog.moreores.item.SliverIngotItem;
import net.browndog.moreores.item.SliverHoeItem;
import net.browndog.moreores.item.SliverAxeItem;
import net.browndog.moreores.item.SliverArmorItem;
import net.browndog.moreores.item.SapphireSwordItem;
import net.browndog.moreores.item.SapphireShovelItem;
import net.browndog.moreores.item.SapphirePickaxeItem;
import net.browndog.moreores.item.SapphireItem;
import net.browndog.moreores.item.SapphireHoeItem;
import net.browndog.moreores.item.SapphireAxeItem;
import net.browndog.moreores.item.SapphireArmorItem;
import net.browndog.moreores.item.RubySwordItem;
import net.browndog.moreores.item.RubyShovelItem;
import net.browndog.moreores.item.RubyPickaxeItem;
import net.browndog.moreores.item.RubyItem;
import net.browndog.moreores.item.RubyHoeItem;
import net.browndog.moreores.item.RubyAxeItem;
import net.browndog.moreores.item.RubyArmorItem;
import net.browndog.moreores.item.Red_DiamondSwordItem;
import net.browndog.moreores.item.Red_DiamondShovelItem;
import net.browndog.moreores.item.Red_DiamondPickaxeItem;
import net.browndog.moreores.item.Red_DiamondItem;
import net.browndog.moreores.item.Red_DiamondHoeItem;
import net.browndog.moreores.item.Red_DiamondAxeItem;
import net.browndog.moreores.item.Red_DiamondArmorItem;
import net.browndog.moreores.item.PurpleDiamondSwordItem;
import net.browndog.moreores.item.PurpleDiamondShovelItem;
import net.browndog.moreores.item.PurpleDiamondPickaxeItem;
import net.browndog.moreores.item.PurpleDiamondItem;
import net.browndog.moreores.item.PurpleDiamondHoeItem;
import net.browndog.moreores.item.PurpleDiamondAxeItem;
import net.browndog.moreores.item.PurpleDiamondArmorItem;
import net.browndog.moreores.item.PlatinumSwordItem;
import net.browndog.moreores.item.PlatinumShovelItem;
import net.browndog.moreores.item.PlatinumPickaxeItem;
import net.browndog.moreores.item.PlatinumIngotItem;
import net.browndog.moreores.item.PlatinumHoeItem;
import net.browndog.moreores.item.PlatinumAxeItem;
import net.browndog.moreores.item.PlatinumArmorItem;
import net.browndog.moreores.item.OrangeDiamondSwordItem;
import net.browndog.moreores.item.OrangeDiamondShovelItem;
import net.browndog.moreores.item.OrangeDiamondPickaxeItem;
import net.browndog.moreores.item.OrangeDiamondItem;
import net.browndog.moreores.item.OrangeDiamondHoeItem;
import net.browndog.moreores.item.OrangeDiamondAxeItem;
import net.browndog.moreores.item.OrangeDiamondArmorItem;
import net.browndog.moreores.item.OpalSwordItem;
import net.browndog.moreores.item.OpalShovelItem;
import net.browndog.moreores.item.OpalPickaxeItem;
import net.browndog.moreores.item.OpalItem;
import net.browndog.moreores.item.OpalHoeItem;
import net.browndog.moreores.item.OpalAxeItem;
import net.browndog.moreores.item.OpalArmorItem;
import net.browndog.moreores.item.NickelSwordItem;
import net.browndog.moreores.item.NickelShovelItem;
import net.browndog.moreores.item.NickelPickaxeItem;
import net.browndog.moreores.item.NickelIngotItem;
import net.browndog.moreores.item.NickelHoeItem;
import net.browndog.moreores.item.NickelAxeItem;
import net.browndog.moreores.item.NickelArmorItem;
import net.browndog.moreores.item.LuminousGemSwordItem;
import net.browndog.moreores.item.LuminousGemShovelItem;
import net.browndog.moreores.item.LuminousGemPickaxeItem;
import net.browndog.moreores.item.LuminousGemItem;
import net.browndog.moreores.item.LuminousGemHoeItem;
import net.browndog.moreores.item.LuminousGemAxeItem;
import net.browndog.moreores.item.LuminousGemArmorItem;
import net.browndog.moreores.item.LithiumSwordItem;
import net.browndog.moreores.item.LithiumShovelItem;
import net.browndog.moreores.item.LithiumPickaxeItem;
import net.browndog.moreores.item.LithiumIngotItem;
import net.browndog.moreores.item.LithiumHoeItem;
import net.browndog.moreores.item.LithiumAxeItem;
import net.browndog.moreores.item.LithiumArmorItem;
import net.browndog.moreores.item.GreenDiamondSwordItem;
import net.browndog.moreores.item.GreenDiamondShovelItem;
import net.browndog.moreores.item.GreenDiamondPickaxeItem;
import net.browndog.moreores.item.GreenDiamondItem;
import net.browndog.moreores.item.GreenDiamondHoeItem;
import net.browndog.moreores.item.GreenDiamondAxeItem;
import net.browndog.moreores.item.GreenDiamondArmorItem;
import net.browndog.moreores.item.BlueDiamondSwordItem;
import net.browndog.moreores.item.BlueDiamondShovelItem;
import net.browndog.moreores.item.BlueDiamondPickaxeItem;
import net.browndog.moreores.item.BlueDiamondItem;
import net.browndog.moreores.item.BlueDiamondHoeItem;
import net.browndog.moreores.item.BlueDiamondAxeItem;
import net.browndog.moreores.item.BlueDiamondArmorItem;
import net.browndog.moreores.item.BlackDiamondSwordItem;
import net.browndog.moreores.item.BlackDiamondShovelItem;
import net.browndog.moreores.item.BlackDiamondPickaxeItem;
import net.browndog.moreores.item.BlackDiamondItem;
import net.browndog.moreores.item.BlackDiamondHoeItem;
import net.browndog.moreores.item.BlackDiamondAxeItem;
import net.browndog.moreores.item.BlackDiamondArmorItem;
import net.browndog.moreores.item.AetheriumSwordItem;
import net.browndog.moreores.item.AetheriumShovelItem;
import net.browndog.moreores.item.AetheriumPickaxeItem;
import net.browndog.moreores.item.AetheriumIngotItem;
import net.browndog.moreores.item.AetheriumHoeItem;
import net.browndog.moreores.item.AetheriumAxeItem;
import net.browndog.moreores.item.AetheriumArmorItem;
import net.browndog.moreores.BrowndogOresMod;

public class BrowndogOresModItems {
	public static Item AETHERIUM_ARMOR_HELMET;
	public static Item AETHERIUM_ARMOR_CHESTPLATE;
	public static Item AETHERIUM_ARMOR_LEGGINGS;
	public static Item AETHERIUM_ARMOR_BOOTS;
	public static Item SLIVER_ARMOR_HELMET;
	public static Item SLIVER_ARMOR_CHESTPLATE;
	public static Item SLIVER_ARMOR_LEGGINGS;
	public static Item SLIVER_ARMOR_BOOTS;
	public static Item AETHERIUM_ORE;
	public static Item AETHERIUM_BLOCK;
	public static Item SLIVER_ORE;
	public static Item SLIVER_BLOCK;
	public static Item AETHERIUM_INGOT;
	public static Item SLIVER_INGOT;
	public static Item AETHERIUM_PICKAXE;
	public static Item AETHERIUM_AXE;
	public static Item AETHERIUM_SWORD;
	public static Item AETHERIUM_SHOVEL;
	public static Item AETHERIUM_HOE;
	public static Item SLIVER_PICKAXE;
	public static Item SLIVER_AXE;
	public static Item SLIVER_SWORD;
	public static Item SLIVER_SHOVEL;
	public static Item SLIVER_HOE;
	public static Item STEEL_ARMOR_HELMET;
	public static Item STEEL_ARMOR_CHESTPLATE;
	public static Item STEEL_ARMOR_LEGGINGS;
	public static Item STEEL_ARMOR_BOOTS;
	public static Item NICKEL_ARMOR_HELMET;
	public static Item NICKEL_ARMOR_CHESTPLATE;
	public static Item NICKEL_ARMOR_LEGGINGS;
	public static Item NICKEL_ARMOR_BOOTS;
	public static Item RUBY_ARMOR_HELMET;
	public static Item RUBY_ARMOR_CHESTPLATE;
	public static Item RUBY_ARMOR_LEGGINGS;
	public static Item RUBY_ARMOR_BOOTS;
	public static Item STEEL_ORE;
	public static Item STEEL_BLOCK;
	public static Item NICKEL_ORE;
	public static Item NICKEL_BLOCK;
	public static Item RUBY_ORE;
	public static Item RUBY_BLOCK;
	public static Item STEEL_INGOT;
	public static Item NICKEL_INGOT;
	public static Item RUBY;
	public static Item STEEL_PICKAXE;
	public static Item STEEL_AXE;
	public static Item STEEL_SWORD;
	public static Item STEEL_SHOVEL;
	public static Item STEEL_HOE;
	public static Item NICKEL_PICKAXE;
	public static Item NICKEL_AXE;
	public static Item NICKEL_SWORD;
	public static Item NICKEL_SHOVEL;
	public static Item NICKEL_HOE;
	public static Item RUBY_PICKAXE;
	public static Item RUBY_AXE;
	public static Item RUBY_SWORD;
	public static Item RUBY_SHOVEL;
	public static Item RUBY_HOE;
	public static Item SAPPHIRE_ARMOR_HELMET;
	public static Item SAPPHIRE_ARMOR_CHESTPLATE;
	public static Item SAPPHIRE_ARMOR_LEGGINGS;
	public static Item SAPPHIRE_ARMOR_BOOTS;
	public static Item TOPAZ_ARMOR_HELMET;
	public static Item TOPAZ_ARMOR_CHESTPLATE;
	public static Item TOPAZ_ARMOR_LEGGINGS;
	public static Item TOPAZ_ARMOR_BOOTS;
	public static Item SAPPHIRE_ORE;
	public static Item SAPPHIRE_BLOCK;
	public static Item TOPAZ_ORE;
	public static Item TOPAZ_BLOCK;
	public static Item SAPPHIRE;
	public static Item TOPAZ;
	public static Item SAPPHIRE_PICKAXE;
	public static Item SAPPHIRE_AXE;
	public static Item SAPPHIRE_SWORD;
	public static Item SAPPHIRE_SHOVEL;
	public static Item SAPPHIRE_HOE;
	public static Item TOPAZ_PICKAXE;
	public static Item TOPAZ_AXE;
	public static Item TOPAZ_SWORD;
	public static Item TOPAZ_SHOVEL;
	public static Item TOPAZ_HOE;
	public static Item OPAL_ARMOR_HELMET;
	public static Item OPAL_ARMOR_CHESTPLATE;
	public static Item OPAL_ARMOR_LEGGINGS;
	public static Item OPAL_ARMOR_BOOTS;
	public static Item OPAL_ORE;
	public static Item OPAL_BLOCK;
	public static Item OPAL;
	public static Item OPAL_PICKAXE;
	public static Item OPAL_AXE;
	public static Item OPAL_SWORD;
	public static Item OPAL_SHOVEL;
	public static Item OPAL_HOE;
	public static Item TITANIUM_ARMOR_HELMET;
	public static Item TITANIUM_ARMOR_CHESTPLATE;
	public static Item TITANIUM_ARMOR_LEGGINGS;
	public static Item TITANIUM_ARMOR_BOOTS;
	public static Item TANZANITE_ARMOR_HELMET;
	public static Item TANZANITE_ARMOR_CHESTPLATE;
	public static Item TANZANITE_ARMOR_LEGGINGS;
	public static Item TANZANITE_ARMOR_BOOTS;
	public static Item LUMINOUS_GEM_ARMOR_HELMET;
	public static Item LUMINOUS_GEM_ARMOR_CHESTPLATE;
	public static Item LUMINOUS_GEM_ARMOR_LEGGINGS;
	public static Item LUMINOUS_GEM_ARMOR_BOOTS;
	public static Item TITANIUM_ORE;
	public static Item TITANIUM_BLOCK;
	public static Item TANZANITE_ORE;
	public static Item TANZANITE_BLOCK;
	public static Item LUMINOUS_GEM_ORE;
	public static Item LUMINOUS_GEM_BLOCK;
	public static Item TITANIUM_INGOT;
	public static Item TANZANITE;
	public static Item LUMINOUS_GEM;
	public static Item TITANIUM_PICKAXE;
	public static Item TITANIUM_AXE;
	public static Item TITANIUM_SWORD;
	public static Item TITANIUM_SHOVEL;
	public static Item TITANIUM_HOE;
	public static Item TANZANITE_PICKAXE;
	public static Item TANZANITE_AXE;
	public static Item TANZANITE_SWORD;
	public static Item TANZANITE_SHOVEL;
	public static Item TANZANITE_HOE;
	public static Item LUMINOUS_GEM_PICKAXE;
	public static Item LUMINOUS_GEM_AXE;
	public static Item LUMINOUS_GEM_SWORD;
	public static Item LUMINOUS_GEM_SHOVEL;
	public static Item LUMINOUS_GEM_HOE;
	public static Item ZINK_ARMOR_HELMET;
	public static Item ZINK_ARMOR_CHESTPLATE;
	public static Item ZINK_ARMOR_LEGGINGS;
	public static Item ZINK_ARMOR_BOOTS;
	public static Item LITHIUM_ARMOR_HELMET;
	public static Item LITHIUM_ARMOR_CHESTPLATE;
	public static Item LITHIUM_ARMOR_LEGGINGS;
	public static Item LITHIUM_ARMOR_BOOTS;
	public static Item TIN_ARMOR_HELMET;
	public static Item TIN_ARMOR_CHESTPLATE;
	public static Item TIN_ARMOR_LEGGINGS;
	public static Item TIN_ARMOR_BOOTS;
	public static Item PLATINUM_ARMOR_HELMET;
	public static Item PLATINUM_ARMOR_CHESTPLATE;
	public static Item PLATINUM_ARMOR_LEGGINGS;
	public static Item PLATINUM_ARMOR_BOOTS;
	public static Item RED_DIAMOND_ARMOR_HELMET;
	public static Item RED_DIAMOND_ARMOR_CHESTPLATE;
	public static Item RED_DIAMOND_ARMOR_LEGGINGS;
	public static Item RED_DIAMOND_ARMOR_BOOTS;
	public static Item ZINK_ORE;
	public static Item ZINK_BLOCK;
	public static Item LITHIUM_ORE;
	public static Item LITHIUM_BLOCK;
	public static Item TIN_ORE;
	public static Item TIN_BLOCK;
	public static Item PLATINUM_ORE;
	public static Item PLATINUM_BLOCK;
	public static Item RED_DIAMOND_ORE;
	public static Item RED_DIAMOND_BLOCK;
	public static Item ZINK_INGOT;
	public static Item LITHIUM_INGOT;
	public static Item TIN_INGOT;
	public static Item PLATINUM_INGOT;
	public static Item RED_DIAMOND;
	public static Item ZINK_PICKAXE;
	public static Item ZINK_AXE;
	public static Item ZINK_SWORD;
	public static Item ZINK_SHOVEL;
	public static Item ZINK_HOE;
	public static Item LITHIUM_PICKAXE;
	public static Item LITHIUM_AXE;
	public static Item LITHIUM_SWORD;
	public static Item LITHIUM_SHOVEL;
	public static Item LITHIUM_HOE;
	public static Item TIN_PICKAXE;
	public static Item TIN_AXE;
	public static Item TIN_SWORD;
	public static Item TIN_SHOVEL;
	public static Item TIN_HOE;
	public static Item PLATINUM_PICKAXE;
	public static Item PLATINUM_AXE;
	public static Item PLATINUM_SWORD;
	public static Item PLATINUM_SHOVEL;
	public static Item PLATINUM_HOE;
	public static Item RED_DIAMOND_PICKAXE;
	public static Item RED_DIAMOND_AXE;
	public static Item RED_DIAMOND_SWORD;
	public static Item RED_DIAMOND_SHOVEL;
	public static Item RED_DIAMOND_HOE;
	public static Item ORANGE_DIAMOND_ARMOR_HELMET;
	public static Item ORANGE_DIAMOND_ARMOR_CHESTPLATE;
	public static Item ORANGE_DIAMOND_ARMOR_LEGGINGS;
	public static Item ORANGE_DIAMOND_ARMOR_BOOTS;
	public static Item ORANGE_DIAMOND_ORE;
	public static Item ORANGE_DIAMOND_BLOCK;
	public static Item YELLOW_DIAMOND_ORE;
	public static Item YELLOW_DIAMOND_BLOCK;
	public static Item ORANGE_DIAMOND;
	public static Item YELLOW_DIAMOND;
	public static Item ORANGE_DIAMOND_PICKAXE;
	public static Item ORANGE_DIAMOND_AXE;
	public static Item ORANGE_DIAMOND_SWORD;
	public static Item ORANGE_DIAMOND_SHOVEL;
	public static Item ORANGE_DIAMOND_HOE;
	public static Item YELLOW_DIAMOND_PICKAXE;
	public static Item YELLOW_DIAMOND_AXE;
	public static Item YELLOW_DIAMOND_SWORD;
	public static Item YELLOW_DIAMOND_SHOVEL;
	public static Item YELLOW_DIAMOND_HOE;
	public static Item BLACK_DIAMOND_ARMOR_HELMET;
	public static Item BLACK_DIAMOND_ARMOR_CHESTPLATE;
	public static Item BLACK_DIAMOND_ARMOR_LEGGINGS;
	public static Item BLACK_DIAMOND_ARMOR_BOOTS;
	public static Item BLACK_DIAMOND_ORE;
	public static Item BLACK_DIAMOND_BLOCK;
	public static Item BLACK_DIAMOND;
	public static Item BLACK_DIAMOND_PICKAXE;
	public static Item BLACK_DIAMOND_AXE;
	public static Item BLACK_DIAMOND_SWORD;
	public static Item BLACK_DIAMOND_SHOVEL;
	public static Item BLACK_DIAMOND_HOE;
	public static Item GREEN_DIAMOND_ARMOR_HELMET;
	public static Item GREEN_DIAMOND_ARMOR_CHESTPLATE;
	public static Item GREEN_DIAMOND_ARMOR_LEGGINGS;
	public static Item GREEN_DIAMOND_ARMOR_BOOTS;
	public static Item BLUE_DIAMOND_ARMOR_HELMET;
	public static Item BLUE_DIAMOND_ARMOR_CHESTPLATE;
	public static Item BLUE_DIAMOND_ARMOR_LEGGINGS;
	public static Item BLUE_DIAMOND_ARMOR_BOOTS;
	public static Item GREEN_DIAMOND_ORE;
	public static Item GREEN_DIAMOND_BLOCK;
	public static Item BLUE_DIAMOND_ORE;
	public static Item BLUE_DIAMOND_BLOCK;
	public static Item GREEN_DIAMOND;
	public static Item BLUE_DIAMOND;
	public static Item GREEN_DIAMOND_PICKAXE;
	public static Item GREEN_DIAMOND_AXE;
	public static Item GREEN_DIAMOND_SWORD;
	public static Item GREEN_DIAMOND_SHOVEL;
	public static Item GREEN_DIAMOND_HOE;
	public static Item BLUE_DIAMOND_PICKAXE;
	public static Item BLUE_DIAMOND_AXE;
	public static Item BLUE_DIAMOND_SWORD;
	public static Item BLUE_DIAMOND_SHOVEL;
	public static Item BLUE_DIAMOND_HOE;
	public static Item PURPLE_DIAMOND_ARMOR_HELMET;
	public static Item PURPLE_DIAMOND_ARMOR_CHESTPLATE;
	public static Item PURPLE_DIAMOND_ARMOR_LEGGINGS;
	public static Item PURPLE_DIAMOND_ARMOR_BOOTS;
	public static Item PURPLE_DIAMOND_ORE;
	public static Item PURPLE_DIAMOND_BLOCK;
	public static Item PURPLE_DIAMOND;
	public static Item PURPLE_DIAMOND_PICKAXE;
	public static Item PURPLE_DIAMOND_AXE;
	public static Item PURPLE_DIAMOND_SWORD;
	public static Item PURPLE_DIAMOND_SHOVEL;
	public static Item PURPLE_DIAMOND_HOE;

	public static void load() {
		AETHERIUM_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_armor_helmet"), new AetheriumArmorItem.Helmet());
		AETHERIUM_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_armor_chestplate"), new AetheriumArmorItem.Chestplate());
		AETHERIUM_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_armor_leggings"), new AetheriumArmorItem.Leggings());
		AETHERIUM_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_armor_boots"), new AetheriumArmorItem.Boots());
		SLIVER_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_armor_helmet"), new SliverArmorItem.Helmet());
		SLIVER_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_armor_chestplate"), new SliverArmorItem.Chestplate());
		SLIVER_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_armor_leggings"), new SliverArmorItem.Leggings());
		SLIVER_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_armor_boots"), new SliverArmorItem.Boots());
		AETHERIUM_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_ore"), new BlockItem(BrowndogOresModBlocks.AETHERIUM_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		AETHERIUM_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_block"), new BlockItem(BrowndogOresModBlocks.AETHERIUM_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		SLIVER_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_ore"), new BlockItem(BrowndogOresModBlocks.SLIVER_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		SLIVER_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_block"), new BlockItem(BrowndogOresModBlocks.SLIVER_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		AETHERIUM_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_ingot"), new AetheriumIngotItem());
		SLIVER_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_ingot"), new SliverIngotItem());
		AETHERIUM_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_pickaxe"), new AetheriumPickaxeItem());
		AETHERIUM_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_axe"), new AetheriumAxeItem());
		AETHERIUM_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_sword"), new AetheriumSwordItem());
		AETHERIUM_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_shovel"), new AetheriumShovelItem());
		AETHERIUM_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "aetherium_hoe"), new AetheriumHoeItem());
		SLIVER_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_pickaxe"), new SliverPickaxeItem());
		SLIVER_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_axe"), new SliverAxeItem());
		SLIVER_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_sword"), new SliverSwordItem());
		SLIVER_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_shovel"), new SliverShovelItem());
		SLIVER_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sliver_hoe"), new SliverHoeItem());
		STEEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_armor_helmet"), new SteelArmorItem.Helmet());
		STEEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_armor_chestplate"), new SteelArmorItem.Chestplate());
		STEEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_armor_leggings"), new SteelArmorItem.Leggings());
		STEEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_armor_boots"), new SteelArmorItem.Boots());
		NICKEL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_armor_helmet"), new NickelArmorItem.Helmet());
		NICKEL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_armor_chestplate"), new NickelArmorItem.Chestplate());
		NICKEL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_armor_leggings"), new NickelArmorItem.Leggings());
		NICKEL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_armor_boots"), new NickelArmorItem.Boots());
		RUBY_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_armor_helmet"), new RubyArmorItem.Helmet());
		RUBY_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_armor_chestplate"), new RubyArmorItem.Chestplate());
		RUBY_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_armor_leggings"), new RubyArmorItem.Leggings());
		RUBY_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_armor_boots"), new RubyArmorItem.Boots());
		STEEL_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_ore"), new BlockItem(BrowndogOresModBlocks.STEEL_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		STEEL_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_block"), new BlockItem(BrowndogOresModBlocks.STEEL_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		NICKEL_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_ore"), new BlockItem(BrowndogOresModBlocks.NICKEL_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		NICKEL_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_block"), new BlockItem(BrowndogOresModBlocks.NICKEL_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		RUBY_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_ore"), new BlockItem(BrowndogOresModBlocks.RUBY_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		RUBY_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_block"), new BlockItem(BrowndogOresModBlocks.RUBY_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		STEEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_ingot"), new SteelIngotItem());
		NICKEL_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_ingot"), new NickelIngotItem());
		RUBY = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby"), new RubyItem());
		STEEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_pickaxe"), new SteelPickaxeItem());
		STEEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_axe"), new SteelAxeItem());
		STEEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_sword"), new SteelSwordItem());
		STEEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_shovel"), new SteelShovelItem());
		STEEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "steel_hoe"), new SteelHoeItem());
		NICKEL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_pickaxe"), new NickelPickaxeItem());
		NICKEL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_axe"), new NickelAxeItem());
		NICKEL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_sword"), new NickelSwordItem());
		NICKEL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_shovel"), new NickelShovelItem());
		NICKEL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "nickel_hoe"), new NickelHoeItem());
		RUBY_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_pickaxe"), new RubyPickaxeItem());
		RUBY_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_axe"), new RubyAxeItem());
		RUBY_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_sword"), new RubySwordItem());
		RUBY_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_shovel"), new RubyShovelItem());
		RUBY_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "ruby_hoe"), new RubyHoeItem());
		SAPPHIRE_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_armor_helmet"), new SapphireArmorItem.Helmet());
		SAPPHIRE_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_armor_chestplate"), new SapphireArmorItem.Chestplate());
		SAPPHIRE_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_armor_leggings"), new SapphireArmorItem.Leggings());
		SAPPHIRE_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_armor_boots"), new SapphireArmorItem.Boots());
		TOPAZ_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_armor_helmet"), new TopazArmorItem.Helmet());
		TOPAZ_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_armor_chestplate"), new TopazArmorItem.Chestplate());
		TOPAZ_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_armor_leggings"), new TopazArmorItem.Leggings());
		TOPAZ_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_armor_boots"), new TopazArmorItem.Boots());
		SAPPHIRE_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_ore"), new BlockItem(BrowndogOresModBlocks.SAPPHIRE_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		SAPPHIRE_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_block"), new BlockItem(BrowndogOresModBlocks.SAPPHIRE_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TOPAZ_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_ore"), new BlockItem(BrowndogOresModBlocks.TOPAZ_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TOPAZ_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_block"), new BlockItem(BrowndogOresModBlocks.TOPAZ_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		SAPPHIRE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire"), new SapphireItem());
		TOPAZ = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz"), new TopazItem());
		SAPPHIRE_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_pickaxe"), new SapphirePickaxeItem());
		SAPPHIRE_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_axe"), new SapphireAxeItem());
		SAPPHIRE_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_sword"), new SapphireSwordItem());
		SAPPHIRE_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_shovel"), new SapphireShovelItem());
		SAPPHIRE_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "sapphire_hoe"), new SapphireHoeItem());
		TOPAZ_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_pickaxe"), new TopazPickaxeItem());
		TOPAZ_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_axe"), new TopazAxeItem());
		TOPAZ_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_sword"), new TopazSwordItem());
		TOPAZ_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_shovel"), new TopazShovelItem());
		TOPAZ_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "topaz_hoe"), new TopazHoeItem());
		OPAL_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_armor_helmet"), new OpalArmorItem.Helmet());
		OPAL_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_armor_chestplate"), new OpalArmorItem.Chestplate());
		OPAL_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_armor_leggings"), new OpalArmorItem.Leggings());
		OPAL_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_armor_boots"), new OpalArmorItem.Boots());
		OPAL_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_ore"), new BlockItem(BrowndogOresModBlocks.OPAL_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		OPAL_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_block"), new BlockItem(BrowndogOresModBlocks.OPAL_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		OPAL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal"), new OpalItem());
		OPAL_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_pickaxe"), new OpalPickaxeItem());
		OPAL_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_axe"), new OpalAxeItem());
		OPAL_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_sword"), new OpalSwordItem());
		OPAL_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_shovel"), new OpalShovelItem());
		OPAL_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "opal_hoe"), new OpalHoeItem());
		TITANIUM_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_armor_helmet"), new TitaniumArmorItem.Helmet());
		TITANIUM_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_armor_chestplate"), new TitaniumArmorItem.Chestplate());
		TITANIUM_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_armor_leggings"), new TitaniumArmorItem.Leggings());
		TITANIUM_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_armor_boots"), new TitaniumArmorItem.Boots());
		TANZANITE_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_armor_helmet"), new TanzaniteArmorItem.Helmet());
		TANZANITE_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_armor_chestplate"), new TanzaniteArmorItem.Chestplate());
		TANZANITE_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_armor_leggings"), new TanzaniteArmorItem.Leggings());
		TANZANITE_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_armor_boots"), new TanzaniteArmorItem.Boots());
		LUMINOUS_GEM_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_armor_helmet"), new LuminousGemArmorItem.Helmet());
		LUMINOUS_GEM_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_armor_chestplate"), new LuminousGemArmorItem.Chestplate());
		LUMINOUS_GEM_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_armor_leggings"), new LuminousGemArmorItem.Leggings());
		LUMINOUS_GEM_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_armor_boots"), new LuminousGemArmorItem.Boots());
		TITANIUM_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_ore"), new BlockItem(BrowndogOresModBlocks.TITANIUM_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TITANIUM_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_block"), new BlockItem(BrowndogOresModBlocks.TITANIUM_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TANZANITE_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_ore"), new BlockItem(BrowndogOresModBlocks.TANZANITE_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TANZANITE_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_block"), new BlockItem(BrowndogOresModBlocks.TANZANITE_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		LUMINOUS_GEM_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_ore"), new BlockItem(BrowndogOresModBlocks.LUMINOUS_GEM_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		LUMINOUS_GEM_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_block"),
				new BlockItem(BrowndogOresModBlocks.LUMINOUS_GEM_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TITANIUM_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_ingot"), new TitaniumIngotItem());
		TANZANITE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite"), new TanzaniteItem());
		LUMINOUS_GEM = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem"), new LuminousGemItem());
		TITANIUM_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_pickaxe"), new TitaniumPickaxeItem());
		TITANIUM_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_axe"), new TitaniumAxeItem());
		TITANIUM_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_sword"), new TitaniumSwordItem());
		TITANIUM_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_shovel"), new TitaniumShovelItem());
		TITANIUM_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "titanium_hoe"), new TitaniumHoeItem());
		TANZANITE_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_pickaxe"), new TanzanitePickaxeItem());
		TANZANITE_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_axe"), new TanzaniteAxeItem());
		TANZANITE_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_sword"), new TanzaniteSwordItem());
		TANZANITE_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_shovel"), new TanzaniteShovelItem());
		TANZANITE_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tanzanite_hoe"), new TanzaniteHoeItem());
		LUMINOUS_GEM_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_pickaxe"), new LuminousGemPickaxeItem());
		LUMINOUS_GEM_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_axe"), new LuminousGemAxeItem());
		LUMINOUS_GEM_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_sword"), new LuminousGemSwordItem());
		LUMINOUS_GEM_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_shovel"), new LuminousGemShovelItem());
		LUMINOUS_GEM_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "luminous_gem_hoe"), new LuminousGemHoeItem());
		ZINK_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_armor_helmet"), new ZinkArmorItem.Helmet());
		ZINK_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_armor_chestplate"), new ZinkArmorItem.Chestplate());
		ZINK_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_armor_leggings"), new ZinkArmorItem.Leggings());
		ZINK_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_armor_boots"), new ZinkArmorItem.Boots());
		LITHIUM_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_armor_helmet"), new LithiumArmorItem.Helmet());
		LITHIUM_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_armor_chestplate"), new LithiumArmorItem.Chestplate());
		LITHIUM_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_armor_leggings"), new LithiumArmorItem.Leggings());
		LITHIUM_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_armor_boots"), new LithiumArmorItem.Boots());
		TIN_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_armor_helmet"), new TinArmorItem.Helmet());
		TIN_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_armor_chestplate"), new TinArmorItem.Chestplate());
		TIN_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_armor_leggings"), new TinArmorItem.Leggings());
		TIN_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_armor_boots"), new TinArmorItem.Boots());
		PLATINUM_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_armor_helmet"), new PlatinumArmorItem.Helmet());
		PLATINUM_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_armor_chestplate"), new PlatinumArmorItem.Chestplate());
		PLATINUM_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_armor_leggings"), new PlatinumArmorItem.Leggings());
		PLATINUM_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_armor_boots"), new PlatinumArmorItem.Boots());
		RED_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_armor_helmet"), new Red_DiamondArmorItem.Helmet());
		RED_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_armor_chestplate"), new Red_DiamondArmorItem.Chestplate());
		RED_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_armor_leggings"), new Red_DiamondArmorItem.Leggings());
		RED_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_armor_boots"), new Red_DiamondArmorItem.Boots());
		ZINK_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_ore"), new BlockItem(BrowndogOresModBlocks.ZINK_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		ZINK_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_block"), new BlockItem(BrowndogOresModBlocks.ZINK_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		LITHIUM_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_ore"), new BlockItem(BrowndogOresModBlocks.LITHIUM_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		LITHIUM_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_block"), new BlockItem(BrowndogOresModBlocks.LITHIUM_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TIN_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_ore"), new BlockItem(BrowndogOresModBlocks.TIN_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		TIN_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_block"), new BlockItem(BrowndogOresModBlocks.TIN_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		PLATINUM_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_ore"), new BlockItem(BrowndogOresModBlocks.PLATINUM_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		PLATINUM_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_block"), new BlockItem(BrowndogOresModBlocks.PLATINUM_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		RED_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_ore"), new BlockItem(BrowndogOresModBlocks.RED_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		RED_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.RED_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		ZINK_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_ingot"), new ZinkIngotItem());
		LITHIUM_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_ingot"), new LithiumIngotItem());
		TIN_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_ingot"), new TinIngotItem());
		PLATINUM_INGOT = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_ingot"), new PlatinumIngotItem());
		RED_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond"), new Red_DiamondItem());
		ZINK_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_pickaxe"), new ZinkPickaxeItem());
		ZINK_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_axe"), new ZinkAxeItem());
		ZINK_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_sword"), new ZinkSwordItem());
		ZINK_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_shovel"), new ZinkShovelItem());
		ZINK_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "zink_hoe"), new ZinkHoeItem());
		LITHIUM_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_pickaxe"), new LithiumPickaxeItem());
		LITHIUM_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_axe"), new LithiumAxeItem());
		LITHIUM_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_sword"), new LithiumSwordItem());
		LITHIUM_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_shovel"), new LithiumShovelItem());
		LITHIUM_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "lithium_hoe"), new LithiumHoeItem());
		TIN_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_pickaxe"), new TinPickaxeItem());
		TIN_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_axe"), new TinAxeItem());
		TIN_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_sword"), new TinSwordItem());
		TIN_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_shovel"), new TinShovelItem());
		TIN_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "tin_hoe"), new TinHoeItem());
		PLATINUM_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_pickaxe"), new PlatinumPickaxeItem());
		PLATINUM_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_axe"), new PlatinumAxeItem());
		PLATINUM_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_sword"), new PlatinumSwordItem());
		PLATINUM_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_shovel"), new PlatinumShovelItem());
		PLATINUM_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "platinum_hoe"), new PlatinumHoeItem());
		RED_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_pickaxe"), new Red_DiamondPickaxeItem());
		RED_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_axe"), new Red_DiamondAxeItem());
		RED_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_sword"), new Red_DiamondSwordItem());
		RED_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_shovel"), new Red_DiamondShovelItem());
		RED_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "red_diamond_hoe"), new Red_DiamondHoeItem());
		ORANGE_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_armor_helmet"), new OrangeDiamondArmorItem.Helmet());
		ORANGE_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_armor_chestplate"), new OrangeDiamondArmorItem.Chestplate());
		ORANGE_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_armor_leggings"), new OrangeDiamondArmorItem.Leggings());
		ORANGE_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_armor_boots"), new OrangeDiamondArmorItem.Boots());
		ORANGE_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_ore"),
				new BlockItem(BrowndogOresModBlocks.ORANGE_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		ORANGE_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.ORANGE_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		YELLOW_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_ore"),
				new BlockItem(BrowndogOresModBlocks.YELLOW_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		YELLOW_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.YELLOW_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		ORANGE_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond"), new OrangeDiamondItem());
		YELLOW_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond"), new YellowDiamondItem());
		ORANGE_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_pickaxe"), new OrangeDiamondPickaxeItem());
		ORANGE_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_axe"), new OrangeDiamondAxeItem());
		ORANGE_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_sword"), new OrangeDiamondSwordItem());
		ORANGE_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_shovel"), new OrangeDiamondShovelItem());
		ORANGE_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "orange_diamond_hoe"), new OrangeDiamondHoeItem());
		YELLOW_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_pickaxe"), new YellowDiamondPickaxeItem());
		YELLOW_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_axe"), new YellowDiamondAxeItem());
		YELLOW_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_sword"), new YellowDiamondSwordItem());
		YELLOW_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_shovel"), new YellowDiamondShovelItem());
		YELLOW_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "yellow_diamond_hoe"), new YellowDiamondHoeItem());
		BLACK_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_armor_helmet"), new BlackDiamondArmorItem.Helmet());
		BLACK_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_armor_chestplate"), new BlackDiamondArmorItem.Chestplate());
		BLACK_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_armor_leggings"), new BlackDiamondArmorItem.Leggings());
		BLACK_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_armor_boots"), new BlackDiamondArmorItem.Boots());
		BLACK_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_ore"),
				new BlockItem(BrowndogOresModBlocks.BLACK_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		BLACK_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.BLACK_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		BLACK_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond"), new BlackDiamondItem());
		BLACK_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_pickaxe"), new BlackDiamondPickaxeItem());
		BLACK_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_axe"), new BlackDiamondAxeItem());
		BLACK_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_sword"), new BlackDiamondSwordItem());
		BLACK_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_shovel"), new BlackDiamondShovelItem());
		BLACK_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "black_diamond_hoe"), new BlackDiamondHoeItem());
		GREEN_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_armor_helmet"), new GreenDiamondArmorItem.Helmet());
		GREEN_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_armor_chestplate"), new GreenDiamondArmorItem.Chestplate());
		GREEN_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_armor_leggings"), new GreenDiamondArmorItem.Leggings());
		GREEN_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_armor_boots"), new GreenDiamondArmorItem.Boots());
		BLUE_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_armor_helmet"), new BlueDiamondArmorItem.Helmet());
		BLUE_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_armor_chestplate"), new BlueDiamondArmorItem.Chestplate());
		BLUE_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_armor_leggings"), new BlueDiamondArmorItem.Leggings());
		BLUE_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_armor_boots"), new BlueDiamondArmorItem.Boots());
		GREEN_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_ore"),
				new BlockItem(BrowndogOresModBlocks.GREEN_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		GREEN_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.GREEN_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		BLUE_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_ore"), new BlockItem(BrowndogOresModBlocks.BLUE_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		BLUE_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.BLUE_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		GREEN_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond"), new GreenDiamondItem());
		BLUE_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond"), new BlueDiamondItem());
		GREEN_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_pickaxe"), new GreenDiamondPickaxeItem());
		GREEN_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_axe"), new GreenDiamondAxeItem());
		GREEN_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_sword"), new GreenDiamondSwordItem());
		GREEN_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_shovel"), new GreenDiamondShovelItem());
		GREEN_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "green_diamond_hoe"), new GreenDiamondHoeItem());
		BLUE_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_pickaxe"), new BlueDiamondPickaxeItem());
		BLUE_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_axe"), new BlueDiamondAxeItem());
		BLUE_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_sword"), new BlueDiamondSwordItem());
		BLUE_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_shovel"), new BlueDiamondShovelItem());
		BLUE_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "blue_diamond_hoe"), new BlueDiamondHoeItem());
		PURPLE_DIAMOND_ARMOR_HELMET = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_armor_helmet"), new PurpleDiamondArmorItem.Helmet());
		PURPLE_DIAMOND_ARMOR_CHESTPLATE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_armor_chestplate"), new PurpleDiamondArmorItem.Chestplate());
		PURPLE_DIAMOND_ARMOR_LEGGINGS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_armor_leggings"), new PurpleDiamondArmorItem.Leggings());
		PURPLE_DIAMOND_ARMOR_BOOTS = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_armor_boots"), new PurpleDiamondArmorItem.Boots());
		PURPLE_DIAMOND_ORE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_ore"),
				new BlockItem(BrowndogOresModBlocks.PURPLE_DIAMOND_ORE, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		PURPLE_DIAMOND_BLOCK = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_block"),
				new BlockItem(BrowndogOresModBlocks.PURPLE_DIAMOND_BLOCK, new Item.Properties().tab(BrowndogOresModTabs.TAB_ORE_CREATIVE_TAB)));
		PURPLE_DIAMOND = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond"), new PurpleDiamondItem());
		PURPLE_DIAMOND_PICKAXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_pickaxe"), new PurpleDiamondPickaxeItem());
		PURPLE_DIAMOND_AXE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_axe"), new PurpleDiamondAxeItem());
		PURPLE_DIAMOND_SWORD = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_sword"), new PurpleDiamondSwordItem());
		PURPLE_DIAMOND_SHOVEL = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_shovel"), new PurpleDiamondShovelItem());
		PURPLE_DIAMOND_HOE = Registry.register(Registry.ITEM, new ResourceLocation(BrowndogOresMod.MODID, "purple_diamond_hoe"), new PurpleDiamondHoeItem());
	}
}
